protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
    {
        return array(
            'upload'=>array(
                'class'=>'xupload.actions.XUploadAction',
                'path' =>Yii::app() -> getBasePath() . "/../uploads",
                'publicPath' => Yii::app() -> getBaseUrl() . "/uploads",
            ),
            'page'=>array(
            	'class'=>'CViewAction',
            ),
        );
    }

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		//Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/protected/extensions/videojs/assets/video.js',CClientScript::POS_BEGIN); 
		//Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/protected/extensions/videojs/assets/video-js.css'); 


		if (!Yii::app()->user->isGuest) {
			$this->layout = 'normal-zamrudpoint';
			$models = Posts::model()->findAll('status = :status', array(':status' => 1));
	  		$model = new Posts;
	  		$model_listens = PostListens::model()->findAll('status = :status', array(':status' => 1));
	  		$model_listen = new PostListens;
	  	
	  		//$model_listens = PostListens::model()->findAll('status = :status', array(':status' => 1));
	  		//$model_listen = new PostListens;

	  		$this->render('index', array('model'=>$model, 'models' => $models, 'model_listens'=>$model_listens, 'model_listen' => $model_listen));
		} else {
			$this->layout = 'home';
			$this->render('index');
		}

		
		/*	
		if (isset($_POST['RegisterForm']))
		{
			$model->attributes = $_POST['RegisterForm'];
			if ($model->validate())
			{
				$user = new User;
				$user->attributes = $_POST['RegisterForm'];
				
				$user->ttl = date("Y-m-d", strtotime($user->ttl));
				
				$user->salt = $user->generateSalt();
				$user->password = $user->hashPassword($user->password, $user->salt);
				$user->last_visit = date("Y-m-d G:i:s");
				$user->join_date = date("Y-m-d");

				$user->picture = CUploadedFile::getInstance($model, 'picture');
				
				if ($user->save()) {
					if ($user->picture) {
						$fileName = $user->username.'.'.$user->picture->extensionName;
						$path = getcwd().'/uploads/account/'.$fileName;
						$user->picture->saveAs($path);
						$user->picture = $fileName;
						$user->save(false); //no validation run
					}
					
					$this->redirect(array('/site/login'));
				} else {
					throw new CHttpException(405, CHtml::errorSummary($user));
				}
			}
		}
		*/

		
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	public function actionRegister(){
		$model = new RegisterForm;
		
		if (isset($_POST['RegisterForm']))
		{
			$model->attributes = $_POST['RegisterForm'];
			if ($model->validate())
			{
				$user = new User;
				$user->attributes = $_POST['RegisterForm'];
				
				/* Format tampilan beda sama format di database. Di tampilan: d-m-Y, di database Y-m-d. */
				$user->ttl = date("Y-m-d", strtotime($user->ttl));
				
				$user->salt = $user->generateSalt();
				$user->password = $user->hashPassword($user->password, $user->salt);
				$user->last_visit = date("Y-m-d G:i:s");
				$user->join_date = date("Y-m-d");
				$user->native_lang_id = 1;
				$user->learn_lang_id = 2;

				$user->picture = CUploadedFile::getInstance($model, 'picture');
				
				if ($user->save()) {
					if ($user->picture) {
						$fileName = $user->username.'.'.$user->picture->extensionName;
						$path = getcwd().'/uploads/account/'.$fileName;
						$user->picture->saveAs($path);
						$user->picture = $fileName;
						$user->save(false); //no validation run
					}
					
					$this->redirect(array('/site/login'));
				} else {
					throw new CHttpException(405, CHtml::errorSummary($user));
				}
			}
		}

		$this->render('register',array('model'=>$model));
	}


	/**
	 * Displays the login page
	 */
	public function actionCheckLogin(){
		if(Yii::app()->user->isGuest){
			echo "false";
		} else {
			echo "true";
		}
	}

	public function actionLogin()
	{	
		if(isset($_GET['fb']) && $_GET['fb'] == 1){
			$model = new LoginFormFB;

			$model->username = "user_fb_".$_POST['fb_id'];
			$model->fb_id = $_POST['fb_id'];

			//belum ada, bikin di database
			if(!$model->checkExist()){
				$user = new User;
				$user->full_name = $_POST['full_name'];
				$user->email = $_POST['email'];
				$user->gender = $_POST['gender'];
				$user->username = "user_fb_".$_POST['fb_id'];
				$user->password = 'Hehehe';
				$user->fb_id = $_POST['fb_id'];
				$user->last_visit = date("Y-m-d G:i:s");
				$user->join_date = date("Y-m-d");
				//default
				$user->native_lang_id = 1;
				$user->learn_lang_id = 2;
				$user->save();
			}

			if($model->login()){
				echo "Hey!";
				$this->redirect(array('site/index'));
			}
			echo "Hey2!";

		} else {
			$model=new LoginForm;

			// if it is ajax validation request
			if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
			{
				echo CActiveForm::validate($model);
				Yii::app()->end();
			}

			// collect user input data
			if(isset($_POST['LoginForm']))
			{
				$model->attributes=$_POST['LoginForm'];
				// validate user input and redirect to the previous page if valid
				if($model->validate() && $model->login())
					$this->redirect(Yii::app()->user->returnUrl);
			}
			// display the login form
			$this->render('login',array('model'=>$model));
		}
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	/**
	 *  Displays the submission page
	 */
	public function actionCreate() 
	{
		//$this->render('create');
	}
	
	public function actionUpload() 
	{
		 echo '<script type="text/javascript"> alert(\'Hi\'); </script>';
	}

  /**
   *  Displays the correction page
   */
  public function actionCorrect()
  {
  	//harusnya jadi parameter
  	$post_id = 1;

  	$models = Advice::model()->findAll('post_id = :post_id', array(':post_id' => $post_id));
  	$model = new Advice;

  	if(isset($_POST['Advice'])){
		$model->attributes=$_POST['Advice'];
		unset($_POST['Advice']);
		
		$model->user_id = Yii::app()->user->id;
		$model->post_id = $post_id;
		$model->date = date("Y-m-d");
		$model->zamrud_points = 0;

		// validate user input and redirect to the previous page if valid
		if($model->save()){
			$this->redirect(array('site/correct')); //<-- harusnya jg pake post id lagi
		}
	}

    $this->render('correct', array('model'=>$model, 'models' => $models));
  }

	public function actionSave(){
		    // Muaz Khan         - www.MuazKhan.com
	    // MIT License       - www.WebRTC-Experiment.com/licence
	    // Documentation     - github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC
	    
	    // make sure that you're using newest ffmpeg version!

	    // because we've different ffmpeg commands for windows & linux
	    // that's why following script is used to fetch target OS
	/*
	    $OSList = array
	    (
	    'Windows 3.11' => 'Win16',
	    'Windows 95' => '(Windows 95)|(Win95)|(Windows_95)',
	    'Windows 98' => '(Windows 98)|(Win98)',
	    'Windows 2000' => '(Windows NT 5.0)|(Windows 2000)',
	    'Windows XP' => '(Windows NT 5.1)|(Windows XP)',
	    'Windows Server 2003' => '(Windows NT 5.2)',
	    'Windows Vista' => '(Windows NT 6.0)',
	    'Windows 7' => '(Windows NT 7.0)',
	    'Windows NT 4.0' => '(Windows NT 4.0)|(WinNT4.0)|(WinNT)|(Windows NT)',
	    'Windows ME' => 'Windows ME',
	    'Open BSD' => 'OpenBSD',
	    'Sun OS' => 'SunOS',
	    'Linux' => '(Linux)|(X11)',
	    'Mac OS' => '(Mac_PowerPC)|(Macintosh)',
	    'QNX' => 'QNX',
	    'BeOS' => 'BeOS',
	    'OS/2' => 'OS/2',
	    'Search Bot'=>'(nuhk)|(Googlebot)|(Yammybot)|(Openbot)|(Slurp)|(MSNBot)|(Ask Jeeves/Teoma)|(ia_archiver)'
	    );
	    // Loop through the array of user agents and matching operating systems
	    foreach($OSList as $CurrOS=>$Match)
	    {
	        // Find a match
	        if (preg_match($Match, $_SERVER['HTTP_USER_AGENT']))
	        {
	            // We found the correct match
	            break;
	        }
	    }
	*/

	    // if it is audio-blob
	    if (isset($_FILES["audio-blob"])) {
	        $uploadDirectory = 'uploads/temp/'.$_POST["filename"].'.wav';
	        if (!move_uploaded_file($_FILES["audio-blob"]["tmp_name"], $uploadDirectory)) {
	            echo("Problem writing audio file to disk!");
	        }
	        else {
	            // if it is video-blob
	            if (isset($_FILES["video-blob"])) {
	                $uploadDirectory = 'uploads/temp/'.$_POST["filename"].'.webm';
	                if (!move_uploaded_file($_FILES["video-blob"]["tmp_name"], $uploadDirectory)) {
	                    echo("Problem writing video file to disk!");
	                }
	                else {

protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1>Contact Us</h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint">Please enter the letters as they are shown in the image above.
		<br/>Letters are not case-sensitive.</div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/index.php
<?php
	/* @var $this SiteController */
	$this->pageTitle = Yii::app()->name;
?>

<?php if (Yii::app()->user->isGuest) { ?>
	<!-- summary -->
	<div class="row text-center space-top">
		<div class="col-lg-offset-2 col-lg-8">
			<h1><i><?= CHtml::encode(Yii::app()->name); ?> <?= Yii::t('home', 'boosts your spoken language experience practically.'); ?></i></h1>
		</div>
	</div><!-- summary -->
	<!-- overview -->
	<div class="row space-top">
		<div class="col-lg-6 text-center">
			<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/speaking.png" alt="Speaking Practice" width="33%">
			<h3><?= Yii::t('home', 'Tell your great stories in your target language.'); ?></h3>
		</div>
		<div class="col-lg-6 text-center">
			<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/listening.png" alt="Listening Practice" width="33%">
			<h3><?= Yii::t('home', 'Listen to your target language spoken by native speaker.'); ?></h3>
		</div>
	</div>
	<div class="row space-top">
		<div class="col-lg-6 text-center">
			<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/advice.png" alt="Speaking Help Others" width="33%">
			<h3><?= Yii::t('home', 'Share your advices with others to help them improving their skill.'); ?></h3>
		</div>
		<div class="col-lg-6 text-center">
			<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/quiz.png" alt="Listening Help Others" width="33%">
			<h3><?= Yii::t('home', 'Create listening quizes to help others learning your native language.'); ?></h3>
		</div>
	</div>
	<div class="row space-top">
		<div class="col-lg-offset-4 col-lg-4">
			<?= CHtml::link(Yii::t('user', 'Register now!'), array('site/register'), array('class' => 'btn btn-primary btn-lg btn-block')); ?>
		</div>
	</div><!-- overview -->
<?php } else { ?>
	<div class="row" id="pagenotitle">
		<div class="col-lg-12 tit_tutrial text-center">
			<b><?= Yii::t('labels', 'What can you do with'); ?> <?= CHtml::encode(Yii::app()->name); ?>?</b>
		</div>
		<div class='col-lg-12 image_body_list' width="100%">
			<div class="col-lg-3 text-center">
				<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/speaking_abu.png" alt="Speaking Practice" width="55%">
				<br><br><?= CHtml::link(Yii::t('labels', 'Practice Speaking'), array('post/create'), array('class' => 'btn btn-primary btn-sm')); ?>
				<h6><?= Yii::t('labels', 'Tell your great stories in your target language'); ?></h6>
			</div>
			<div class="col-lg-3 text-center">
				<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/listening_abu.png" alt="Listening Practice" width="55%">
				<br><br><?= CHtml::link(Yii::t('labels', 'Practice Listening'), array('postListen/index'), array('class' => 'btn btn-primary btn-sm')); ?>
				<h6><?= Yii::t('labels', 'Listen to your target language spoken by native speaker'); ?></h6>
			</div>
			<div class="col-lg-3 text-center">
				<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/advice_abu.png" alt="Speaking Help Others" width="55%">
				<br><br><?= CHtml::link(Yii::t('labels', 'Help Others Speaking'), array('post/index'), array('class' => 'btn btn-primary btn-sm')); ?>
				<h6><?= Yii::t('labels', 'Share your advices with others to help them improving their skill'); ?></h6>
			</div>
			<div class="col-lg-3 text-center">
				<img src="<?= Yii::app()->request->baseUrl; ?>/res/img/quiz_abu.png" alt="Listening Help Others" width="55%">
				<br><br><?= CHtml::link(Yii::t('labels', 'Help Others Listening'), array('postListen/index'), array('class' => 'btn btn-primary btn-sm')); ?>
				<h6><?= Yii::t('labels', 'Create listening quizes to help others learning your native language'); ?></h6>
			</div>
		</div>
	</div><!-- pagenotitle -->
	<div class="row" id="pagecontent">
		<div class="col-lg-12 space-top">
			<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
				<li class="active"><a href="#speaking" data-toggle="tab"><?= Yii::t('labels', 'Speaking'); ?></a></li>
				<li><a href="#listening" data-toggle="tab"><?= Yii::t('labels', 'Listening'); ?></a></li>
			</ul>
			<div id="my-tab-content" class="tab-content">
				<div class="tab-pane active" id="speaking">
					<?= CHtml::link(Yii::t('user', '<span class="fa-stack">
					<i class="fa fa-video-camera"></i>
					<i class="fa fa-pencil fa-stack-1x"></i>
					</span>'.Yii::t('labels', 'Create Video for Practice Speaking')), array('post/create'), array('class' => 'btn btn-warning btn-sm pull-right space-top')); ?>
					<div class="col-lg-12 space-top">
						<ul class="media-list">
							<!-- Video -->
							<?php
								foreach($models as $model) {
									$model_advices = Advice::model()->findAll('post_id = :post_id', array(':post_id' => $model->id));
									$video_thumb = Videos::model()->findByAttributes(array('post_id'=> $model->id))->thumbnail;
									$komen = count($model_advices);
							?>
							<li class="media media-list-highlight">
								<a class="pull-left" href="#">
									<img class="media-object"  src="<?php echo Yii::app()->request->baseUrl?>/uploads/thumbnail/<?php echo $video_thumb?>" alt="video thumbnail" width="144" height="96">
								</a>
								<div class="btn-group pull-right">
									<button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown">
										<small><?= Yii::t('labels', 'More');?> <span class="glyphicon glyphicon-collapse-down"></span></small>
									</button>
									<ul class="dropdown-menu" role="menu">
										<li>
											<a href=""><small><?= Yii::t('labels', 'Mark as spam'); ?></small></a>
										</li>
									</ul>
								</div>
								<div class="media-body">
									<h4 class="media-heading">
										<a href="<?php echo Yii::app()->request->baseUrl?>/post/correct?post_id=<?= $model->id ?>"><?= Posts::getTitle($model->id) ?></a>
										<a href=""><small><?= Posts::getLang($model->id); ?></small></a><br>
									</h4>
									<div class="media-subheading"><small><?= Yii::t('labels', 'by'); ?> <a href=""><?= User::getFullName($model->user_id) ?></a></small></div>
									<div class="media-content"><?= Posts::getContent($model->id) ?></div>
									<div class="media-footer">
										<a><i class="fa fa-thumbs-o-up"></i> <small><?= Posts::getLike($model->id) ?> <?= Yii::t('labels', 'vote up'); ?></small></a>
										<span class="tab"></span>
										<a ><i class="fa fa-thumbs-o-down"></i> <small><?= Posts::getDislike($model->id) ?> <?= Yii::t('labels', 'vote down'); ?></small></a>
										<span class="tab"></span>
										<a ><i class="fa fa-user"></i> <small><?= Posts::getWatch($model->id) ?> <?= Yii::t('labels', 'watch'); ?></small></a>
										<span class="tab"></span>
										<a ><i class="fa fa-quote-right"></i> <small><?= $komen ?> <?= Yii::t('labels', 'advice'); ?></small></a>
										<span class="tab"></span>
										<span><small><?= Posts::getDate($model->id) ?></small></span>
									</div>
								</div>
							</li>
							<?php } ?>
						</ul>
					</div>
				</div>
				<div class="tab-pane" id="listening">
					<?= CHtml::link(Yii::t('user', '  <span class="fa-stack">
					<i class="fa fa-film"></i>
					<i class="fa fa-pencil fa-stack-1x"></i>
					</span>'.Yii::t('labels', 'Create Video to Help Other Listening')), array('post/create'), array('class' => 'btn btn-warning btn-sm pull-right space-top')); ?>
					<div class="col-lg-12 space-top">
						<ul class="media-list">
							<!-- Video -->
							<?php
								foreach($model_listens as $model_listen) {
									//$model_advices = Advice::model()->findAll('post_id = :post_id', array(':post_id' => $model->id));
									$video_thumb = VideoListens::model()->findByAttributes(array('post_listen_id'=> $model_listen->id))->thumbnail;
									//$komen = count($model_advices);
							?>
							<li class="media media-list-highlight">
								<a class="pull-left" href="#">
									<img class="media-object"  src="<?php echo Yii::app()->request->baseUrl?>/uploads/thumbnail_listens/<?php echo $video_thumb?>" alt="video thumbnail" width="144" height="96">
								</a>
								<div class="btn-group pull-right">
									<button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown">
										<small><?= Yii::t('labels', 'More');?> <span class="glyphicon glyphicon-collapse-down"></span></small>
									</button>
									<ul class="dropdown-menu" role="menu">
										<li>
											<a href=""><small><?= Yii::t('labels', 'Mark as spam'); ?></small></a>
										</li>
									</ul>
								</div>
								<div class="media-body">
									<h4 class="media-heading">
										<a href="<?php echo Yii::app()->request->baseUrl?>/postListens/quizes?id=<?= $model_listen->id ?>"><?= PostListens::getTitle($model_listen->id) ?></a>
										<a href=""><small><?= PostListens::getLang($model_listen->id); ?></small></a><br>
									</h4>
									<div class="media-subheading"><small><?= Yii::t('labels', 'by'); ?> <a href=""><?= User::getFullName($model_listen->user_id) ?></a></small></div>
									<div class="media-content">
										Theme: <?= Themes::model()->findByAttributes(array('id'=> $model_listen->theme_id))->name ?> 
										<br>
										Topic: <?= Topics::model()->findByAttributes(array('id'=> $model_listen->topic_id))->name ?> 
									</div>
									<div class="media-footer">
										<a ><i class="fa fa-thumbs-o-up"></i> <small><?= PostListens::getLike($model_listen->id) ?> <?= Yii::t('labels', 'vote up'); ?></small></a>
										<span class="tab"></span>
										<a ><i class="fa fa-thumbs-o-down"></i> <small><?= PostListens::getDislike($model_listen->id) ?> <?= Yii::t('labels', 'vote down'); ?></small></a>
										<span class="tab"></span>
										<a ><i class="fa fa-user"></i> <small>- <?= Yii::t('labels', 'watch'); ?></small></a>
										<span class="tab"></span>
										<span><small><?= Posts::getDate($model->id) ?></small></span>
									</div>
								</div>
							</li>
							<?php } ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div><!-- pagecontent -->
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$('#tabs').tab();
		});
	</script>
<?php } ?>

protected/views/site/login.php
<?php $this->pageTitle=Yii::app()->name . ' - Log In'; ?>

<div class="row">
  <div class="col-lg-12 box effect2">
    <?php $form=$this->beginWidget('booster.widgets.TbActiveForm', array(
      'id'=>'login-form',
      'enableClientValidation'=>true,
      'clientOptions'=>array(
          'validateOnSubmit'=>true,
      ),
      'htmlOptions' => array('class' => 'col-lg-offset-3 col-lg-6 well')
    )); ?>

    <legend><?= Yii::t('user', 'Log In'); ?></legend>

    <?php echo $form->textFieldGroup($model,'username'); ?>

    <?php echo $form->passwordFieldGroup($model,'password'); ?>

    <?php echo $form->checkBoxGroup($model,'rememberMe'); ?>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary pull-right"><?= Yii::t('user', 'Log In'); ?></button>
      <a class="btn btn-link pull-right" href="<?= Yii::app()->createUrl('site/register') ?>"><?= Yii::t('user', 'Register'); ?></a>
    </div>

    <?php $this->endWidget(); ?>

    <div class="col-lg-offset-3 col-lg-6 text-center">
      <div class="col-lg-12 hr-container">
        <hr class="hr-line">
        <span class="hr-text"><strong><?= Yii::t('common', 'or'); ?></strong></span>
      </div>
      <div class="col-lg-4">
        <?php
          $this->widget('booster.widgets.TbButton', array(
            'block' => true,
            'encodeLabel' => false,
            'buttonType' => 'submit',
            'context' => 'info',
            'label' => '<i class="fa fa-facebook-square fa-lg"></i> Facebook',
            'htmlOptions' => array('onclick'=>'checkLoginState();'),
          ));
        ?>
      </div>
      <div class="col-lg-4">
        <?php
          $this->widget('booster.widgets.TbButton', array(
            'block' => true,
            'encodeLabel' => false,
            'buttonType' => 'submit',
            'context' => 'primary',
            'label' => '<i class="fa fa-twitter-square fa-lg"></i> Twitter',
          ));
        ?>
      </div>
      <div class="col-lg-4">
        <?php
          $this->widget('booster.widgets.TbButton', array(
            'block' => true,
            'encodeLabel' => false,
            'buttonType' => 'submit',
            'context' => 'danger',
            'label' => '<i class="fa fa-google-plus-square fa-lg"></i> Google+',
          ));
        ?>
      </div>
      </div>
    </div>
  </div>
</div>